app: 
  name: "api-gateway"
  version: "0.0.1"

server:
  port: "8080"
  timeout: 30

logger:
  level: "debug"

auth:
  address: "50051"
  timeout: 30

user:
  address: "50052"
  timeout: 30

gpt:
  address: "50053"
  timeout: 30